/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbCopilotRouteImport } from './routes/db-copilot'
import { Route as IndexRouteImport } from './routes/index'

const DbCopilotRoute = DbCopilotRouteImport.update({
  id: '/db-copilot',
  path: '/db-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db-copilot': typeof DbCopilotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db-copilot': typeof DbCopilotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db-copilot': typeof DbCopilotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/db-copilot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db-copilot'
  id: '__root__' | '/' | '/db-copilot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbCopilotRoute: typeof DbCopilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/db-copilot': {
      id: '/db-copilot'
      path: '/db-copilot'
      fullPath: '/db-copilot'
      preLoaderRoute: typeof DbCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbCopilotRoute: DbCopilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
